return {
  { "L3MON4D3/LuaSnip",           enabled = false },
  { "rcarriga/cmp-dap",           enabled = false },
  { "stevearc/dressing.nvim",     enabled = false },
  { "RRethy/vim-illuminate",      enabled = false },
  { "folke/todo-comments.nvim",   enabled = false },
  { "stevearc/resession.nvim",    enabled = false },
  { "sar/friendly-snippets.nvim", enabled = false },
  { "NMAC427/guess-indent.nvim",  enabled = false },
  { "folke/neoconf.nvim",         enabled = false },
  { "stevearc/resession.nvim",    enabled = false },
  { "s1n7ax/nvim-window-picker",  enabled = false },
  { "mfussenegger/nvim-dap",      enabled = false },
  { "rcarriga/nvim-dap-ui",       enabled = false },
}
